[event_0001]
event = "start"
git_sha = "bea357ede785da465557c74e577405f413fd3e3e"
host = "Blah"
platform = "Windows-11-10.0.26200-SP0"
python = "3.13.5"
run_id = "20251224_202438_smoke_cpu"
run_name = "smoke_cpu"
started_utc = "2025-12-24T20:24:38.567549+00:00"
